checks:
  exclude:
    # CSI drivers require hostNetwork for kubelet communication
    - "host-network"
    # CSI node daemonset requires privileged access for disk mounting operations
    - "privileged-container"
    - "privilege-escalation-container"
    # CSI drivers need to run as root for disk operations
    - "run-as-non-root"
    # CSI drivers need writable filesystem for socket and state management
    - "no-read-only-root-fs"
    # CSI node requires access to /dev for block device operations
    - "sensitive-host-mounts"
    # When using hostNetwork, explicit containerPort declarations aren't required
    - "liveness-port"
    # Anti-affinity is configured via topology constraints, not pod anti-affinity
    - "no-anti-affinity"

